### ISSUE TITLE
Script terminated when running as a thread

### ISSUE THREAD

**Issue by cafeitduong** [UnkL4b/GitMiner#17]
Hi,

Your script is very helpful in searching for my company sensitive leakage on github.com, recently I face the problem that when I run the script as a thread or put it in a crontab for example: 

` python git_miner.py --query 'filename:configuration extension:php "public password" in:file' -m joomla -c pAAAhPOma9jEsXyLWZ-16RTTsGI8wDawbNs4 &`

It's randomly terminated without an error message, I don't know if it is terminated by github.com or not? Do you have any idea?

Thanks.

**Comment by MatthiasMaltes** [comment]
Hey, I'm writing my Bachelor Thesis about "finding similarities in code from GitHub" . For this Bachelor Thesis I need a lot of code. Now I saw that your tool could help me to find a lot of code but all searches I try to type into your GitMiner Program didn't find any results. These are the searches I've typed in:
python git_miner.py -q 'extension:h #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:hpp #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:c #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:h #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:hpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:c #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:test extension:h #pragma omp in:file ' -o result.txt

In his Program he's using the coockie from his own Github account, where can I find it?
Please help me than otherwise I have to open every github page and copy the code and download it.

Kind regards

Matthias Maltes﻿
Matthias.Mlates@gmail.com

**Comment by cafeitduong** [comment]
Hi Matthias,

To find your github's cookies, you can use any cookies add-ons on your browser, I'm using 'EditthisCookie' on Chrome. Then with the obtained cookies, put it in -c you will see result appears!

Sorry for late respond.

**Comment by danilovazb** [comment]
It has been fixed in version 2.0.

Github has changed the way presented the search results, I had to redo the crawler.
