### ISSUE TITLE
error msg each time I am launching GitMiner

### ISSUE THREAD

**Issue by syrius01** [UnkL4b/GitMiner#18]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

Any help would be very appreciated,

Thanks.

**Comment by MatthiasMaltes** [comment]
Hey, I'm writing my Bachelor Thesis about "finding similarities in code from GitHub" . For this Bachelor Thesis I need a lot of code. Now I saw that your tool could help me to find a lot of code but all searches I try to type into your GitMiner Program didn't find any results. These are the searches I've typed in:
python git_miner.py -q 'extension:h #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:hpp #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:c #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:h #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:hpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:c #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:test extension:h #pragma omp in:file ' -o result.txt

In his Program he's using the coockie from his own Github account, where can I find it?
Please help me than otherwise I have to open every github page and copy the code and download it.

Kind regards

Matthias Maltes﻿
Matthias.Mlates@gmail.com
